### ISSUE TITLE
👏

### ISSUE THREAD

**Issue by iCrawl** [HyperCoder2975/vsc-discord-rpc#3]
This is really nice and all, even that you published it.

But you reuse a TON of code I have written, you didn't even bother changing any of it. License files exist for a reason, and the way this is not a fork is the biggest joke I guess.

But hey, you do you. Convoluting the vscode extension ecosystem with another module that practically is just a direct copy of mine seems good.

**Comment by HyperCoder2975** [comment]
I'm pretty sure my code is quite different than yours. I rewrote it and made quite a lot of changes. I wanted my own extension with what I wanted to be able to do, so I think this is justified.

**Comment by iCrawl** [comment]
https://github.com/HyperCoder2975/vsc-discord-rpc/blob/6f8d33d9bf2989dd4872a0a93a4484f3108c794e/extension.js#L3

Let's not even mention that this isn't even needed when you write pure JS instead of TS, but how would you know. Timers only get imported for typings.

https://github.com/HyperCoder2975/vsc-discord-rpc/blob/6f8d33d9bf2989dd4872a0a93a4484f3108c794e/extension.js#L82-L87

https://github.com/HyperCoder2975/vsc-discord-rpc/blob/6f8d33d9bf2989dd4872a0a93a4484f3108c794e/extension.js#L91-L103

https://github.com/HyperCoder2975/vsc-discord-rpc/blob/6f8d33d9bf2989dd4872a0a93a4484f3108c794e/extension.js#L113-L129

You didn't bother changing any of the logic or renaming the variables even. My point still stands, I have a license file and everyone can see that you took a lot of the code and "jsified" it.

**Comment by GetRektByMe** [comment]
@iCrawl please do not steal this man's hard work! He worked very hard, I think you might have actually copied off of him and you are just really jealous that he is a better coder than you!!!

**Comment by iCrawl** [comment]
Also this thing here is the logo of my extension, just saying: 
https://github.com/HyperCoder2975/vsc-discord-rpc/blob/master/assets/vsc.png

**Comment by SirPacker** [comment]
@iCrawl, lets put it this way: Hyper took your TS extension, converted it to JS, made it into a class, and then added features that you didn't have. Maybe if you were not so head-strong, you would have noticed his credit in the repo description. Go pick on someone else, as this is not your place.

**Comment by iCrawl** [comment]
Complying/Respecting a license agreement has nothing to do with being headstrong.
And changing all variable names after I pointed them out to something else just to not include the license file is a dickish move.

I don't care if you take his site or not, this is an issue and it needed to be pointed out.

**Comment by HyperCoder2975** [comment]
I didn't copy it and change a couple of things. I rewrote it and made a lot of changes to that. I didn't "take" and "modify" code at this point. Earlier, it was a lot like yours. I then rewrote it, which isn't a modification-it's a new script.

**Comment by GetRektByMe** [comment]
Actually, it looks pretty modified to me tbh. Rewriting the variable names and slightly adjusting how it works doesn't make it a new script.

**Comment by KyeNormanGill** [comment]
rewrote what? his code. exactly. case closed. you're all going to jail

**Comment by SirPacker** [comment]
@iCrawl, fair enough, but the code was already rewritten before you even added a license. Grandfathering is in effect with this repo: http://cheezewerks.com/u/38188.png

**Comment by iCrawl** [comment]
Admitting that grandfathering is in place would mean you actually took code from it, which he absolutely denies.

Like I said, I don't care anymore. As long as you get rid of any icons or whatever that can be confused with my extension, because that was not the case either. As long as this is done you can go your way and do whatever.

**Comment by HyperCoder2975** [comment]
I do not deny taking code, although I made a new script after messing with your code based on your code. Not everything was changed, but quite a bit was.

**Comment by iCrawl** [comment]
I take this as resolved then (seeing as you removed the icon too).
