### ISSUE TITLE
That was mean sir

### ISSUE THREAD

**Issue by GetRektByMe** [HyperCoder2975/vsc-discord-rpc#6]
It is very rude to close an unsolved issue to collaborators when you don't want to hear about code you have stolen and not given due credit for sir!

**Comment by HyperCoder2975** [comment]
Check the description of the depository. Says right there.

**Comment by KingDGrizzle** [comment]
`To have a language added, submit a pull request adding to the supported languages list and add a 512x512 png image with the language's icon.` 👌
